# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f67b1b3eda32112f0addc29baf498c13681cfb97184251ce7a1af1f7f4398b49c41218242df7256f832abf820e93c343d34c8d212a983fc8a7bfd3897d9f95fb
  devise_pepper: <%= ENV["DEVISE_PEPPER"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
  mailer_address: <%= ENV["MAILER_ADDRESS"] %>
  mailer_user_name: <%= ENV["MAILER_USER_NAME"] %>
  mailer_password: <%= ENV["MAILER_PASSWORD"] %>
  mailer_host: <%= ENV["MAILER_HOST"] %>
  weibo_key: <%= ENV["WEIBO_KEY"] %>
  weibo_secret: <%= ENV["WEIBO_SECRET"] %>
  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  google_key: <%= ENV["GOOGLE_KEY"] %>
  google_secret: <%= ENV["GOOGLE_SECRET"] %>
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>

test:
  secret_key_base: f82989352ffa63c924fadc1f9c4f26a0a80a701213682f08ed4de512516e022cdb075d11942c84c3e20aa03e3070f620ce78464b6a4fa7e184c15d007e83856e
  devise_pepper: <%= ENV["DEVISE_PEPPER"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
  mailer_address: <%= ENV["MAILER_ADDRESS"] %>
  mailer_user_name: <%= ENV["MAILER_USER_NAME"] %>
  mailer_password: <%= ENV["MAILER_PASSWORD"] %>
  mailer_host: <%= ENV["MAILER_HOST"] %>
  weibo_key: <%= ENV["WEIBO_KEY"] %>
  weibo_secret: <%= ENV["WEIBO_SECRET"] %>
  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  google_key: <%= ENV["GOOGLE_KEY"] %>
  google_secret: <%= ENV["GOOGLE_SECRET"] %>
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_pepper: <%= ENV["DEVISE_PEPPER"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
  mailer_address: <%= ENV["MAILER_ADDRESS"] %>
  mailer_user_name: <%= ENV["MAILER_USER_NAME"] %>
  mailer_password: <%= ENV["MAILER_PASSWORD"] %>
  mailer_host: <%= ENV["MAILER_HOST"] %>
  weibo_key: <%= ENV["WEIBO_KEY"] %>
  weibo_secret: <%= ENV["WEIBO_SECRET"] %>
  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  google_key: <%= ENV["GOOGLE_KEY"] %>
  google_secret: <%= ENV["GOOGLE_SECRET"] %>
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
